---- insert into forum(id ,username ,title) values (1,'test@gmail.com','forum item test' );
---- insert into chat_message(id, username ,message, forum_id) values (1,'test2@gmail.com','jakas wiadomosc 1', 1);
---- insert into chat_message(id, username ,message, forum_id) values (2,'test1@gmail.com','jakas wiadomosc 2', 1);

--insert into account(name ,username ,password) values ('test','test@gmail.com','$2a$10$NC0w5gQR/wU76aih.t652eere5F0T3YV/03MdBNcP4QQUAkmOjP8u' );

--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values (/', 'home', 3, 'drwxr-xr-x','root', 'root','true', 4096, '', 'Jul 31 22:29');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values (/', 'bin', 1, 'lrwxrwxrwx','root', 'root','true', 9, '', 'Jun  9 09:53');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values (/', 'boot', 5, 'drwxr-xr-x','root', 'root','true', 4096, '', 'Jul 31 22:32');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values (/', 'dev', 19, 'drwxr-xr-x','root', 'root','true', 4200, '', 'Aug  7 10:31');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values (/', 'etc', 106, 'drwxr-xr-x','root', 'root','true', 4096, '', 'Aug  7 10:31');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values (/', 'lib', 1, 'lrwxrwxrwx','root', 'root','true', 7, '', 'Jun  9 09:53');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values (/', 'proc', 348, 'dr-xr-xr-x','root', 'root','true', 0, '', '');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/', 'root', 2, 'drwxr-x---','root', 'root','true', 19, '', 'Aug  7 10:31');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/', 'run', 3, 'drwxr-xr-x','root', 'root','true', 840, '', 'Aug  7 10:31');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/', 'sbin', 1, 'lrwxrwxrwx','root', 'root','true', 7, '', 'Jun  9 09:53');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/', 'srv', 4, 'drwxr-xr-x','root', 'root','true', 4096, '', 'Jul 29 14:32');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/', 'sys', 13, 'dr-xr-xr-x','root', 'root','true', 0, '', 'Aug  7 10:31');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/', 'tmp', 14, 'drwxrwxrwt','root', 'root','true', 380, '', 'Aug  7 11:15');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/', 'usr', 9, 'drwxr-xr-x','root', 'root','true', 4096, '', 'Aug  5 16:42');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/', 'var', 12, 'dr-xr-xr-x','root', 'root','true', 4096, '', '');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/', 'mnt', 2, 'drwxr-xr-x','root', 'root','true', 4096, '', 'Jun  9 09:53');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home', 'user', 14, 'drwx------','root', 'root','true', 4096, '', 'Jul 30 20:29');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home', '.', 3, 'drwxr-xr-x','root', 'root','true', 4096, '', 'Jul 31 22:29');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home', '..', 17, 'drwxr-xr-x','root', 'root','true', 4096, '', 'Jul 29 14:09');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', '.', 22, 'drwx------','root', 'root','true', 4096, '', 'Aug  7 10:51');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', '..', 3, 'drwxr-xr-x','root', 'root','true', 4096, '', 'Jul 31 22:29');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', 'Desktop', 2, 'drwxr-xr-x','', '','true', 4096, '', 'Aug  6 00:01');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', 'Documents', 2, 'drwxr-xr-x','', '','true', 4096, '', 'Aug  6 00:23');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', 'Downloads', 2, 'drwxr-xr-x','', '','true', 4096, '', 'Jul 31 22:33');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', 'Music', 2, 'drwxr-xr-x','', '','true', 4096, '', 'Jul 31 22:33');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', 'Pictures', 2, 'drwxr-xr-x','', '','true', 4096, '', 'Jul 31 22:33');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', 'Public', 2, 'drwxr-xr-x','', '','true', 4096, '', 'Jul 31 22:33');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', 'Templates', 2, 'drwxr-xr-x','', '','true', 4096, '', 'Jul 31 22:33');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', 'Videos', 2, 'drwxr-xr-x','', '','true', 4096, '', 'Jul 31 22:33');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', '.config', 17, 'drwxr-xr-x','', '','true', 4096, '', 'Aug  5 16:38');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', '.cache', 14, 'drwxr-xr-x','', '','true', 4096, '', 'Aug  1 01:48');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', '.bash_histor', 1, '-rw-------','', '','false', 5146, 'some code', 'Aug  7 01:02');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', '.bash_logout', 1, '-rw-r--r--','', '','false', 21, 'some code', 'Jan  9  2022');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', '.bash_profile', 1, '-rw-r--r--','', '','false', 57, 'some code', 'Jan  9  2022');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', '.bashrc', 1, '-rw-r--r--','', '','false', 3878, 'some code', 'Aug  1 00:05');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', '.nanorc', 1, '-rw-r--r--','', '','false', 53, 'some code', 'Jun  3 16:272');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', 'file.txt', 1, '-rw-r--r--','', '','false', 0, 'hello,how are you', 'Jun 20 16:27');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', 'test_file.txt', 1, '-rw-r--r--','', '','false', 0, 'hello orld!', 'Jun 25 10:00');
--insert into vfs(path ,name  ,link  ,permisions ,username  ,groupname ,is_directory ,size ,text ,time ) values ('/home/', 'plik.txt', 1, '-rw-r--r--','', '','false', 0, 'Hello Dżimi', 'Aug  20 09:05');

--INSERT INTO history(account_id, history)
--VALUES
--   ('272d1714-3cb8-42e9-bc50-7794849a48af','["cat file.txt", "cd .."]')
--RETURNING *;
